services:
  - type: pserv
    name: nats
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: NATS_SERVER
        value: "nats://nats:4222"
    healthCheckPath: /healthz
    ports:
      - port: 8222
        protocol: http
